export const LOAD_CONFIGURATIONS = 'LOAD_CONFIGURATIONS';
export const LOAD_MANIFESTS = 'LOAD_MANIFESTS';
export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT';
export const SET_TRANSFORMER_CONTENT = 'SET_TRANSFORMER_CONTENT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
