// Auth
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

// Configurations
export const LOAD_CONFIGURATIONS = 'LOAD_CONFIGURATIONS';

// Manifests
export const LOAD_MANIFESTS = 'LOAD_MANIFESTS';

// App
export const API_REQUEST = 'API_REQUEST';

// Editors
export const SET_TITLE = 'SET_TITLE';
export const LOAD_SELECTION = 'LOAD_SELECTION';
export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT';
export const SET_TRANSFORMER_CONTENT = 'SET_TRANSFORMER_CONTENT';