// Auth
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// Configurations
export const LOAD_CONFIGURATIONS = 'LOAD_CONFIGURATIONS';

// Manifests
export const LOAD_MANIFESTS = 'LOAD_MANIFESTS';

// App
export const SET_ERROR = 'SET_ERROR';
export const API_REQUEST = 'API_REQUEST';

// Editors
export const SET_TITLE = 'SET_TITLE';

export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT';
export const SET_TRANSFORMER_CONTENT = 'SET_TRANSFORMER_CONTENT';

// Nanny Editor
export const SET_NANNY_EDITOR = 'SET_NANNY_EDITOR';
export const LOAD_SELECTION = 'LOAD_SELECTION';

// API KEY
export const GENERATE_APIKEY_RESPONSE = "GENERATE_APIKEY_RESPONSE";

// USERS

export const GET_USERS_RESPONSE = "GET_USERS_RESPONSE";
export const UPDATE_CREATE_USER = "UPDATE_CREATE_USER";

// APIKEYS
export const GENEREATE_APIKEY_REQUEST = "GENEREATE_APIKEY_REQUEST";
export const GENEREATE_APIKEY_REPSONSE = "GENEREATE_APIKEY_REPSONSE";

export const GET_APIKEY_REQUEST = "GET_APIKEY_REQUEST";
export const GET_APIKEY_REPSONSE = "GET_APIKEY_REPSONSE>";

export const GET_USER_APIKEY_REQUEST = "GET_USER_APIKEY_REQUEST";
export const GET_USER_APIKEY_EPSONSE = "GET__USER_APIKEY_REPSONSE>";

export const DELETE_APIKEY_REQUEST = "DELETE_APIKEY_REQUEST";
export const DELETE_APIKEY_REPSONSE = "DELETE_APIKEY_REPSONSE>";

export const PUT_APIKEY_REQUEST = "PUT_APIKEY_REQUEST";
export const PUT_APIKEY_REPSONSE = "<PUT_APIKEY_REPSONSE>";
